//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazer_Eyes.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lazer_Eyes.Resources.Languages.ApplicationResource", typeof(ApplicationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string AlertS {
            get {
                return ResourceManager.GetString("AlertS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notifications are initially set to default. You can customize them by going to the Notifications page. You can change the intensity and volume of the sound. You can also adjust the intensity of vibration. Vibration and sound can also be turned off. You can choose to disable notifications for low light. .
        /// </summary>
        internal static string AnswerFive {
            get {
                return ResourceManager.GetString("AnswerFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can customize settings by going in the General page. You can choose the units you preffer for distance measurement, choose at what distance you want to be notified for an obsticle by setting a distance threshold..
        /// </summary>
        internal static string AnswerFour {
            get {
                return ResourceManager.GetString("AnswerFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We recommend you consult with a Orientation and Mobility specialist before use. The App requires you to point the camera in the direction you are walking and it will notify you of various objects in your path and their distance. .
        /// </summary>
        internal static string AnswerOne {
            get {
                return ResourceManager.GetString("AnswerOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lazer Eyes utilizes LIDAR and therefore you would need specific phone models such as iPhone 13 Pro, and Pro Max, along with the 5.0 generation iPad Pro..
        /// </summary>
        internal static string AnswerSix {
            get {
                return ResourceManager.GetString("AnswerSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default you will hear sound, feel vibration and have visuals on the Main page of the App..
        /// </summary>
        internal static string AnswerThree {
            get {
                return ResourceManager.GetString("AnswerThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will recieve warnings about objects in your path and low light levels based on your Settings..
        /// </summary>
        internal static string AnswerTwo {
            get {
                return ResourceManager.GetString("AnswerTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditory.
        /// </summary>
        internal static string Auditory {
            get {
                return ResourceManager.GetString("Auditory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger.
        /// </summary>
        internal static string Danger {
            get {
                return ResourceManager.GetString("Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Threshold:.
        /// </summary>
        internal static string DistanceT {
            get {
                return ResourceManager.GetString("DistanceT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Units.
        /// </summary>
        internal static string DistanceU {
            get {
                return ResourceManager.GetString("DistanceU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Distance in Strides.
        /// </summary>
        internal static string DistInStrides {
            get {
                return ResourceManager.GetString("DistInStrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        internal static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting Quality: Good.
        /// </summary>
        internal static string GoodLight {
            get {
                return ResourceManager.GetString("GoodLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, have a question?.
        /// </summary>
        internal static string HelpLabel {
            get {
                return ResourceManager.GetString("HelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        internal static string Intensity {
            get {
                return ResourceManager.GetString("Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Light.
        /// </summary>
        internal static string LowL {
            get {
                return ResourceManager.GetString("LowL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Light Threshold (Lumens).
        /// </summary>
        internal static string LowLThresh {
            get {
                return ResourceManager.GetString("LowLThresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        internal static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting Quality: Poor.
        /// </summary>
        internal static string PoorLight {
            get {
                return ResourceManager.GetString("PoorLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lazer Eyes does not collect any Personal Information. We do not use any tracking software..
        /// </summary>
        internal static string PrivacyAnswer {
            get {
                return ResourceManager.GetString("PrivacyAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q: How do I customize the notifications I will receive?.
        /// </summary>
        internal static string QuestionFive {
            get {
                return ResourceManager.GetString("QuestionFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q: How do I customize settings?.
        /// </summary>
        internal static string QuestionFour {
            get {
                return ResourceManager.GetString("QuestionFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q: How do I use LazerEyes?.
        /// </summary>
        internal static string QuestionOne {
            get {
                return ResourceManager.GetString("QuestionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q: What requirements do I need to use the functionalities of LazerEyes?.
        /// </summary>
        internal static string QuestionSix {
            get {
                return ResourceManager.GetString("QuestionSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q: What kind of notifications will I receive?.
        /// </summary>
        internal static string QuestionThree {
            get {
                return ResourceManager.GetString("QuestionThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q: What kind of alerts will I get?.
        /// </summary>
        internal static string QuestionTwo {
            get {
                return ResourceManager.GetString("QuestionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning....
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        internal static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stride Length:.
        /// </summary>
        internal static string StrideL {
            get {
                return ResourceManager.GetString("StrideL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration.
        /// </summary>
        internal static string Vibration {
            get {
                return ResourceManager.GetString("Vibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        internal static string Warnings {
            get {
                return ResourceManager.GetString("Warnings", resourceCulture);
            }
        }
    }
}
