name: build docs

on: 
  push:
    branches: 
      - main
      - documentation

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    
    env: 
      DOCS_PATH: '/Lazer_Eyes/Docs/Docs.csproj'
      
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK '6.0'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'
      - name: Install dependencies
        run: dotnet restore $GITHUB_WORKSPACE$DOCS_PATH
      - name: Build
        run: dotnet build $GITHUB_WORKSPACE$DOCS_PATH --configuration Release --no-restore
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: docs
          folder: ./Lazer_Eyes/Docs/_site
   
